//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.07 at 11:52:14 AM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:crimsonlogic:tn:schema:xsd:LogService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cl.services;
